spring:
  datasource:
    url: jdbc:mysql://192.168.23.9:3306/tuling?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  redis:
    host: 192.168.23.9 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

#支付成功后的回调方法请求路径以及二维码生成后的磁盘保存路径,以及对应磁盘物理路径的服务器映射路径
ouzo:
  trade:
    qrcode:
      paySuccessCallBack: http://ouzo.gz2vip.91tunnel.com/order/paySuccess
      storePath: C:/1501/javaei/aliqrcode
      httpBasePath: /static/qrcode
